services:
  db:
    image: postgres:16  # Use a specific version, not 'latest'
    container_name: my_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=Aayush
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: